[workspace]
members = ["libcec-sys", "libcec"]
resolver = "2"

[profile.dev.package.backtrace]
opt-level = 3

# [patch.crates-io]
# libcec-sys = { path = "../libcec-sys" }
# cec-rs = { path = ".rg./cec-rs" }
