[workspace]
resolver = "2"
members = ["owl", "cec_sys", "cec"]

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
debug = true

[workspace.lints.clippy]
pedantic = "warn"
suspicious = "warn"
complexity = "warn"
perf = "warn"
