[package]
name = "cec_sys_bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1"
bindgen = "0.69"
color-eyre = "0.6"
reqwest = { version = "0.12", features = ["blocking"] }
zip-extract = "0.1"
bcmp = "0.4"
tempfile = "3"
clap = { version = "4", features = ["derive"] }
