name: test-owl-windows
description: Tests owl on Windows environments.

inputs:
  target:
    description: The target triple being tested.
    required: true
  rust_toolchain:
    description: The Rust toolchain to use.
    required: true

runs:
  using: composite
  steps:
    - name: Setup Rust cache toolchain
      run: rustup toolchain install ${{ inputs.rust_toolchain }} --profile default
      shell: bash

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Check if target bindings exist
      id: check_bindings_exist
      shell: bash
      run: |
        if [ -f 'cec_sys/src/bindings/${{ inputs.target }}.rs'  ]; then
          echo 'BINDINGS_EXIST="true"' >> "$GITHUB_OUTPUT"
        else
          echo 'BINDINGS_EXIST="false"' >> "$GITHUB_OUTPUT"
        fi

    - name: Generate missing bindings
      if: ${{ steps.check_bindings_exist.outputs.bindings_exist }} == 'false'
      run: cargo run --bin cec_bindgen
      shell: pwsh

    - name: Run debug tests
      run: cargo test
      shell: pwsh

    - name: Run release tests
      run: cargo test --release
      shell: pwsh

    - name: Regenerate bindings
      if: ${{ steps.check_bindings_exist.outputs.bindings_exist }} == 'true'
      run: cargo run --bin cec_bindgen
      shell: pwsh

    - name: Commit bindings
      if: ${{ steps.check_bindings_exist.outputs.bindings_exist }} == 'true'
      uses: EndBug/add-and-commit@v9
      with:
        add: cec_sys/src/bindings/${{ inputs.target }}.rs
        message: Update ${{ inputs.target }} libcec bindings
        pathspec_error_handling: exitImmediately
