permissions:
  contents: read

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run bindgen
        run: |
          rustup toolchain install stable --profile minimal
          cargo run --bin cec_bindgen

      - name: Run debug tests
        run: cargo test

      - name: Run release tests
        run: cargo test --release

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run bindgen
        run: nix develop --command cargo run --bin cec_bindgen

      - name: Run debug tests
        run: nix develop --command cargo test

      - name: Run release tests
        run: nix develop --command cargo test --release

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run bindgen
        run: nix develop --command cargo run --bin cec_bindgen

      - name: Run debug tests
        run: nix develop --command cargo test

      - name: Run release tests
        run: nix develop --command cargo test --release
