name: Test owl

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  test-windows:
    runs-on: windows-latest
    env:
      LIBCLANG_PATH: 'C:\Program Files\LLVM\lib'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test owl
        uses: ./.github/actions/test-owl-windows
        with:
          target: x86_64-pc-windows-msvc

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test owl
        uses: ./.github/actions/test-owl-unix
        with:
          target: aarch64-apple-darwin

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test owl
        uses: ./.github/actions/test-owl-unix
        with:
          target: x86_64-unknown-linux-gnu
