permissions:
  contents: read

on:
  push:
    branches: [main]

env:
  RUST_TOOLCHAIN: nightly-2024-09-20

jobs:
  test-windows:
    runs-on: windows-latest
    env:
      LIBCLANG_PATH: 'C:\Program Files\LLVM\lib'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test owl
        uses: ./.github/actions/test-owl-unix
        with:
          target: x86_64-pc-windows-msvc
          rust_toolchain: ${{ env.RUST_TOOLCHAIN }}

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test owl
        uses: ./.github/actions/test-owl-unix
        with:
          target: aarch64-apple-darwin
          rust_toolchain: ${{ env.RUST_TOOLCHAIN }}

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test owl
        uses: ./.github/actions/test-owl-unix
        with:
          target: x86_64-unknown-linux-gnu
          rust_toolchain: ${{ env.RUST_TOOLCHAIN }}
